---
title: "nyt_final_proj"
author: "Jerrica Li"
date: "4/3/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include = FALSE}
library(tidyverse)
library(purrr)
library(broom)
library(dplyr)
library(infer)
library(ggplot2)
library(ggthemes)
library(lubridate)
library(dplyr)
library(tidycensus)
library(janitor)
library(sp)
library(leaflet)
library(rgdal)
library(googlesheets)
library(gganimate)
library(schoolmath)
library(gt)
library(webshot)
library(transformr)
```

```{r reading data}
#state data from NYT
state_data <- read.csv("covid-19-data/us-states.csv") 

#county data from NYT
county_data <- read.csv('covid-19-data/us-counties.csv')

#current testing numbers from tracking project
testing <- read.csv("covid-19-data/yes.csv")

#historical testing numbers from tracking project
test_history <- read.csv("covid-19-data/test_historical.csv")

#mapfiles from US Census
us.map.state <- readOGR(dsn= 'us_state_map', layer = "cb_2018_us_state_5m", stringsAsFactors = FALSE)

us.map.state <- us.map.state[!us.map.state$STATEFP %in% c("69","64", "68", "70", "74"),]

us.map.state <- us.map.state[!us.map.state$STATEFP %in% c("81", "84", "86", "87", "89", "71", "76","95", "79"),]
```

```{r cleaning data}

#clean testing data so names are right
test_clean <- testing %>% 
  clean_names() %>%
  rename(GEOID = fips,
         positive_test = positive, 
         negative_test = negative, 
         total_test = total_test_results) %>%
  select(state,
         GEOID,
         positive_test,
         negative_test,
         total_test) 

#clean test_history so dates are class date
test_history <- test_history %>% 
  mutate(date = ymd(date)) %>%
  clean_names() %>%
  select(-total, 
         -pos_neg)

#clean state data so dates are class "date
state_data <- 
  state_data %>% 
  mutate(new_date = as_date(date),
         GEOID = fips) %>% 
  select(-date, -fips) %>% 
  mutate(date = new_date)

#clean state data so dates are class "date
county_data <- 
  county_data %>% 
  mutate(new_date = as_date(date),
         geoid = as.character(fips)) %>% 
  select(-date, -fips) %>% 
  rename(date = new_date)

```

```{r wrangling test_history}


test_hist_3 <- test_history %>%
  filter(state %in% c("NY", "NJ", "MA"))

pop_3 <- population %>% 
  filter(
    NAME %in% c("New York", "New Jersey", "Massachusetts"), 
    variable == "POP"
    ) %>%
  rename(pop = "value",
         state = "NAME") %>%
  select(-variable)

pop_3[1, "state"] <- "MA"
pop_3[2, "state"] <- "NJ"
pop_3[3, "state"] <- "NY"


omg_1 <- test_hist_3 %>% 
  left_join(pop_3, by = "state") %>%
  mutate(people_per_test = (pop/total_test_results),
         perc_pos = (positive/total_test_results),
         state = as.factor(state)) %>% 
  select(state, perc_pos, people_per_test, date)
omg_1 %>% group_by(state) %>% arrange(desc(perc_pos))

omg_1 %>%
  ggplot(aes(x = people_per_test, y = perc_pos, color = state)) + 
  geom_line() +
  theme_minimal() +
  transition_states(state, transition_length = 5, state_length = 1) +
  view_follow() +
   ggtitle('Now showing {closest_state}',
          subtitle = 'Frame {frame} of {nframes}')

  
  

```

```{r wrangle for clean testing data}
state_latest_yes <- state_data %>% 
  filter(date == latest_date)

joined_test <- test_clean %>% 
  full_join(state_latest_yes, by = "GEOID") %>% 
  rename(state = state.y) %>% 
  select(
    -state.x,
    -new_date,
    -date
         )


joined_test <- joined_test 

population <- get_estimates(geography = "state",
                            product = "population")

pop <- population %>%
  rename(state = NAME, 
         population = value) %>% 
  mutate(GEOID = as.integer(GEOID)) %>%
  select(-variable) 

popu = pop[1:52,]

testing_full <- joined_test %>%
  full_join(popu, by = "GEOID") %>% 
  filter(!is.na(state.y)) %>% 
  rename(state = state.x)

```

```{r data wrangling with testing dataset}
test <- testing_full %>%
  select(-state.y) %>%
  mutate(people_per_test = (population/total_test)) %>%
  mutate(perc_positive = (positive_test/total_test)) %>%
  mutate(trouble = (perc_positive * people_per_test))

test_2 <- test_1 %>% 
  mutate(state = as.character(state))

map_1 <- merge(us.map.state, test_2, by.x = "NAME", by.y = "state")

popup_dat <- paste0("<strong>State: </strong>",
                    map$state,
                    "<br><strong> Number of cases: </strong>",
                    map$cases)

  leaflet(data = map) %>% 
      addTiles() %>%
    setView(-96, 37.8, 4) %>%
      addPolygons(fillColor = ~pal(trouble),
                  fillOpacity = 0.8,
                  color = "#BDBDC3",
                  weight = 1,
                  popup = popup_dat) %>%
      addLegend("bottomright", pal = pal, values = ~trouble,
                title = "Trouble Index",
                opacity = 1 )


```

```{r leaflet}

latest_date <- county_data %>% 
  filter(state == "Washington") %>% 
  arrange(desc(date)) %>% 
  slice(1) %>% 
  pull(date)

state_new <- state_data %>% 
  filter(date == latest_date) %>% 
  mutate(GEOID = as.character(GEOID), 
         state = as.character(state)) %>% 
  select(GEOID, cases, state, deaths)

leafmap <- merge(us.map.state, state_new, by.x = "NAME", by.y = "state")

state_new
troublemap <- 
glimpse(us.map.state)

popup_dat <- paste0("<strong>State: </strong>",
                    leafmap$NAME,
                    "<br><strong> Number of cases: </strong>",
                    leafmap$cases)
pal <- colorNumeric("RdYlGn", NULL, n = 10)


  leaflet(data = leafmap) %>% 
      addTiles() %>%
      addPolygons(fillColor = ~pal(cases),
                  fillOpacity = 0.8,
                  color = "#BDBDC3",
                  weight = 1,
                  popup = popup_dat) %>%
      addLegend("bottomright", pal = pal, values = ~cases,
                title = "Number of cases",
                opacity = 1 )

#transform values keeping in mind your range is from 0-100000
#log might be good to change colors or manually define shades 
#try hotspot states like new jersey or ny 
  #try selecting palates based on number of cases 
  #addProviderTiles(provider = "CartoDB.Positron")
#More things to try:
#death rates, death rates plotted by county / state and to see is it rural places? urban cities? the south? 
#by state, see population size over case rate, 
summary(test)

ok <- tibble("Variable" = c("Min", "1st Qu.", "Median", "Mean", "3rd Qu.", "Max."), 
              "Value" = c(.5782, 3.4116, 5.6641, 6.7036, 8.8152, 47.3151))
glimpse(trouble_map)
trouble<- ok %>% gt() %>% 
tab_header(
    title = "Trouble Index Statistics")
  webshot::install_phantomjs()
trouble %>%
gtsave("trouble_stat.png", path = "raw_data" )

state_data

```


```{r tab three change in cases over time}
wash <- state_data %>% 
  filter(state == "Washington", state == "California")

wash$change <- NA
for(i in 2:nrow(wash)){
  wash$change[i] <- wash$cases[i] - wash$cases[i - 1]
}

plot(log(wash$cases), log(wash$change), type = 'l')

```



```{r plotting, include = FALSE}

ggplot(wash, aes(x = new_date, y = cases)) +
  geom_line() +
  geom_point() + 
  theme_minimal() +

  theme(axis.text.x = element_text(angle = 70, hjust = 1), 
        panel.grid.major = element_blank()) + 
  labs(title = "Confirmed Corona Cases by State (Washington)", 
       x = "date", 
       y = "confirmed cases") +
  scale_x_date(date_breaks = "2 days", date_labels = "%b %d") +
  #geom_area from this github https://gist.github.com/jtrive84/b1a5d191358883dea1d511d8c78929b6#file-ggplot_auc-r-L9
  
  geom_area(mapping=aes(x=new_date), fill="#9898fb", alpha=.5) 
  
  #I was looking at this https://stackoverflow.com/questions/47667994/ggplot-x-axis-labels-with-all-x-axis-values for the longest time before I realized that I can change this by using scale_x_date()

```

```{r saving data}
saveRDS(county_data, file = "nyt_corona/county_data.rds")
saveRDS(state_data, file = "nyt_corona/state_data.rds")
saveRDS(leafmap, file = "nyt_corona/leafmap")
saveRDS(test, file = "nyt_corona/test.rds")
saveRDS(map_1, file = "nyt_corona/trouble_map_PR.rds")
```

```{r}
glimpse(leafmap)
theme_set(theme_bw())
three <- three %>% 
  arrange(state) %>%  
  group_by(state) %>% 
 slice(which(row_number() %% 7 == 1))



three$last <- NA
for(i in 2:nrow(three)){
  three$last[i] <- three$cases[i] - three$cases[i - 1]}

logplot <- three %>% 
            filter(!is.negative(change)) %>% 
            mutate(log_case = log(cases))

plot(log(wash$cases), log(wash$change), type = 'l')

new_three<- three %>% 
  mutate(log_case = log(cases))

wow %>%
ggplot(aes(x = log_case , y = log(last), color = state)) +
  geom_line() +
  geom_point() + 
  theme_minimal() +
  labs(title = "Confirmed Corona Cases by State", 
       x = "Confirmed cases", 
       y = "New cases") +
  transition_reveal(log_case)


wow <- state_data %>% 
  filter(state %in% c("Colorado", "Maine", "New York")) %>% 
  arrange(state) %>%  
  group_by(state) %>% 
 slice(which(row_number() %% 7 == 1))
wow$last <- NA
for(i in 2:nrow(wow)){
  wow$last[i] <- wow$cases[i] - wow$cases[i - 1]}
leafmap 
wow$last[wow$last == 0] <- 1
wow$last[is.na(wow$last)] <- 1
wow <- wow %>% 
        mutate(log_case = log(cases))

```
```{r}
pal <- colorNumeric("YlOrRd", NULL, n = 10)
glimpse(map_1)
            
            popup_dat <- paste0("<strong>State: </strong>",
                                map_1$NAME,
                                "<br><strong> Index: </strong>",
                                map_1$people_per_test)
            state_new
            leaflet(data = map_1) %>% 
                addTiles() %>%
                setView(-96, 37.8, 4) %>%
                addPolygons(fillColor = ~pal(people_per_test),
                            fillOpacity = 0.8,
                            color = "#BDBDC3",
                            weight = 1,
                            popup = popup_dat) %>%
                addLegend("bottomright", pal = pal, values = ~people_per_test,
                          title = "People Per Test",
                          opacity = 1 )
```

